# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-08 18:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_wrongnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Member')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessfulCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Member')),
            ],
        ),
        migrations.RenameField(
            model_name='note',
            old_name='author',
            new_name='logged_by',
        ),
        migrations.RenameField(
            model_name='wrongnumber',
            old_name='reported_by',
            new_name='logged_by',
        ),
    ]
