# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20170202_2320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accueil',
            new_name='Article',
        ),
    ]
