# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-15 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='query',
            field=models.CharField(help_text="eg: { 'federation': 64, }", max_length=5000),
        ),
    ]
