# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoning', '0002_auto_20160517_0757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoningOperation',
            new_name='Operation',
        ),
    ]
