# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoning', '0003_auto_20160518_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='slug',
        ),
    ]
