# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0008_wrongnumber'),
        ('phoning', '0004_remove_operation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='max_requests',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='operation',
            name='targets_called_successfully',
            field=models.ManyToManyField(related_name='targets_called_successfully', to='fichiers_adherents.Adherent'),
        ),
    ]
