# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_adherent', models.IntegerField(verbose_name="Numéro d'adhérent")),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('federation', models.IntegerField(blank=True, null=True)),
                ('date_premiere_adhesion', models.DateField(blank=True, null=True)),
                ('date_derniere_cotisation', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=5, null=True)),
                ('adresse1', models.CharField(blank=True, max_length=1000, null=True)),
                ('adresse2', models.CharField(blank=True, max_length=1000, null=True)),
                ('adresse3', models.CharField(blank=True, max_length=1000, null=True)),
                ('adresse4', models.CharField(blank=True, max_length=1000, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('pays', models.CharField(blank=True, max_length=255, null=True)),
                ('npai', models.CharField(blank=True, max_length=255, null=True)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_portable', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_bureau', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_domicile', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('mandats', models.CharField(blank=True, max_length=255, null=True)),
                ('commune', models.CharField(blank=True, max_length=255, null=True)),
                ('canton', models.CharField(blank=True, max_length=255, null=True)),
                ('a_jour_de_cotisation', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': b'adh\xc3\xa9rent',
                'ordering': ['nom'],
                'get_latest_by': 'date_derniere_cotisation',
                'verbose_name_plural': b'adh\xc3\xa9rents',
                'permissions': (('lecture_fichier_national', 'peut lire le fichier national'),),
            },
        ),
        migrations.CreateModel(
            name='Cnil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('signature', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=255, verbose_name='fait à')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Déclaration CNIL',
                'verbose_name_plural': 'Déclarations CNIL',
            },
        ),
        migrations.CreateModel(
            name='Droits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('query', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name': b"droit d'acc\xc3\xa8s",
                'ordering': ['name'],
                'verbose_name_plural': b"droits d'acc\xc3\xa8s",
            },
        ),
        migrations.CreateModel(
            name='FichierAdherents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_d_import', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('fichier_csv', models.FileField(null=True, upload_to='fichiers_adherents/')),
                ('importateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fichier',
                'ordering': ['-date'],
                'get_latest_by': 'date',
                'verbose_name_plural': 'fichiers',
                'permissions': (('peut_televerser', 'peut charger les nouveaux fichiers adhérents'),),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='fichiers_adherents.Adherent')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('droits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichiers_adherents.Droits')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecteur',
            },
        ),
        migrations.CreateModel(
            name='WrongNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichiers_adherents.Adherent')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='droits',
            name='readers',
            field=models.ManyToManyField(through='fichiers_adherents.Reader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adherent',
            name='fichier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fichiers_adherents.FichierAdherents'),
        ),
    ]
