# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 00:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_adherent', models.IntegerField()),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('federation', models.IntegerField(blank=True, null=True)),
                ('date_premiere_adhesion', models.DateField(blank=True, null=True)),
                ('date_derniere_cotisation', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=5, null=True)),
                ('adresse1', models.CharField(blank=True, max_length=1000, null=True)),
                ('adresse2', models.CharField(blank=True, max_length=1000, null=True)),
                ('adresse3', models.CharField(blank=True, max_length=1000, null=True)),
                ('adresse4', models.CharField(blank=True, max_length=1000, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('pays', models.CharField(blank=True, max_length=255, null=True)),
                ('npai', models.CharField(blank=True, max_length=255, null=True)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_portable', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_bureau', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_domicile', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('mandats', models.CharField(blank=True, max_length=255, null=True)),
                ('commune', models.CharField(blank=True, max_length=255, null=True)),
                ('canton', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['nom'],
                'verbose_name_plural': b'adh\xc3\xa9rents',
                'verbose_name': b'adh\xc3\xa9rent',
            },
        ),
        migrations.CreateModel(
            name='FichierAdherents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_d_import', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255)),
                ('fichier_csv', models.FileField(upload_to='fichiers_adherents/')),
                ('importateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': b'fichiers adh\xc3\xa9rents',
                'permissions': (('peut_televerser', 'peut téléverser'),),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='fichiers_adherents.Adherent')),
            ],
        ),
        migrations.CreateModel(
            name='WrongNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichiers_adherents.Adherent')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='adherent',
            name='fichier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fichiers_adherents.FichierAdherents'),
        ),
    ]
