# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='notes',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
