# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='pas_encore_trop_vieux',
            field=models.BooleanField(default=True),
        ),
    ]
