# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-15 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichieradherents',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'permissions': (('peut_televerser', 'peut charger les nouveaux fichiers adhérents'),), 'verbose_name': 'fichier', 'verbose_name_plural': 'fichiers'},
        ),
        migrations.AddField(
            model_name='adherent',
            name='a_jour_de_cotisation_pour_ce_fichier',
            field=models.BooleanField(default=False),
        ),
    ]
