# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adherent',
            options={'get_latest_by': 'date_derniere_cotisation', 'ordering': ['nom'], 'verbose_name': b'adh\xc3\xa9rent', 'verbose_name_plural': b'adh\xc3\xa9rents'},
        ),
        migrations.AlterModelOptions(
            name='fichieradherents',
            options={'get_latest_by': 'date_derniere_cotisation', 'permissions': (('peut_televerser', 'peut téléverser'),), 'verbose_name_plural': b'fichiers adh\xc3\xa9rents'},
        ),
        migrations.AddField(
            model_name='fichieradherents',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adherent',
            name='fichier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fichiers_adherents.FichierAdherents'),
        ),
    ]
