# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fichiers_adherents', '0002_auto_20161106_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Droits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('query', models.CharField(max_length=5000)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': b"droits d'acc\xc3\xa8s",
                'verbose_name': b"droit d'acc\xc3\xa8s",
            },
        ),
        migrations.AlterModelOptions(
            name='adherent',
            options={'get_latest_by': 'date_derniere_cotisation', 'ordering': ['nom'], 'permissions': (('lecture_fichier_national', 'peut lire le fichier national'),), 'verbose_name': b'adh\xc3\xa9rent', 'verbose_name_plural': b'adh\xc3\xa9rents'},
        ),
        migrations.AlterModelOptions(
            name='fichieradherents',
            options={'get_latest_by': 'date_derniere_cotisation', 'permissions': (('peut_televerser', 'peut charger les nouveaux fichiers adhérents'),), 'verbose_name_plural': b'fichiers adh\xc3\xa9rents'},
        ),
        migrations.AddField(
            model_name='adherent',
            name='actuel',
            field=models.BooleanField(default=False),
        ),
    ]
