# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0002_adherent_pas_encore_trop_vieux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherent',
            name='pas_encore_trop_vieux',
        ),
        migrations.AddField(
            model_name='adherent',
            name='trop_vieux',
            field=models.BooleanField(default=False),
        ),
    ]
