# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-15 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0002_auto_20170115_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichieradherents',
            name='fichier_csv',
            field=models.FileField(null=True, upload_to='fichiers_adherents/'),
        ),
    ]
