# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 01:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fichiers_adherents', '0002_adherent_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='notes_date_last_modified',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adherent',
            name='notes_last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
