# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-15 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0003_auto_20170115_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherent',
            name='a_jour_de_cotisation_pour_ce_fichier',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='actuel',
        ),
    ]
