# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0003_auto_20161113_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='num_adherent',
            field=models.IntegerField(verbose_name="Numéro d'adhérent"),
        ),
    ]
