# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 16:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fichiers_adherents', '0003_auto_20160513_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='notes_date_last_modified',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='notes_last_modified_by',
        ),
        migrations.AddField(
            model_name='note',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichiers_adherents.Adherent'),
        ),
    ]
