# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0003_auto_20170127_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droits',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
