# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0004_auto_20160513_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='fichiers_adherents.Adherent'),
        ),
    ]
