# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0004_auto_20161113_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichieradherents',
            name='slug',
        ),
    ]
