# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-15 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0004_auto_20170115_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='a_jour_de_cotisation',
            field=models.BooleanField(default=False),
        ),
    ]
