# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0004_auto_20170127_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droits',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
