# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0005_auto_20170127_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='target',
        ),
        migrations.AddField(
            model_name='note',
            name='num_adherent',
            field=models.IntegerField(default=0, verbose_name="Numéro d'adhérent"),
            preserve_default=False,
        ),
    ]
