# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0005_auto_20160517_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateDeCotisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': b'dates de cotisation',
                'ordering': ['-date'],
                'verbose_name': b'date de cotisation',
            },
        ),
        migrations.AlterModelOptions(
            name='adherent',
            options={'ordering': ['nom'], 'verbose_name': b'adh\xc3\xa9rent', 'verbose_name_plural': b'adh\xc3\xa9rents'},
        ),
        migrations.AlterModelOptions(
            name='adherentdufichier',
            options={'ordering': ['nom'], 'verbose_name': b'adh\xc3\xa9rent du fichier', 'verbose_name_plural': b'adh\xc3\xa9rents du fichier'},
        ),
        migrations.AddField(
            model_name='adherent',
            name='dates_de_cotisation',
            field=models.ManyToManyField(related_name='dates_de_cotisation', to='fichiers_adherents.DateDeCotisation'),
        ),
    ]
