# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('fichiers_adherents', '0005_remove_fichieradherents_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('signature', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=255, verbose_name='fait à')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
