# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-31 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0006_auto_20170204_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
