# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 22:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0006_cnil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droits',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
