# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0006_auto_20160522_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherent',
            name='dates_de_cotisation',
        ),
        migrations.AddField(
            model_name='datedecotisation',
            name='adherents',
            field=models.ManyToManyField(related_name='adherents_du_jour', to='fichiers_adherents.Adherent'),
        ),
    ]
