# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 00:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fichiers_adherents', '0007_auto_20160522_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrongNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichiers_adherents.Adherent')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
