# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-08 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0007_auto_20170331_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adherent',
            options={'get_latest_by': 'fichier', 'ordering': ['nom'], 'permissions': (('lecture_fichier_national', 'peut lire le fichier national'),), 'verbose_name': b'adh\xc3\xa9rent', 'verbose_name_plural': b'adh\xc3\xa9rents'},
        ),
    ]
