# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 23:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('fichiers_adherents', '0007_auto_20161119_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesFichier',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Utilisateurs ayant accès à une partie du fichier',
                'verbose_name': 'Utilisateur ayant accès à une partie du fichier',
            },
        ),
        migrations.AlterModelOptions(
            name='cnil',
            options={'verbose_name': 'Déclaration CNIL', 'verbose_name_plural': 'Déclarations CNIL'},
        ),
        migrations.RemoveField(
            model_name='droits',
            name='users',
        ),
        migrations.AlterField(
            model_name='cnil',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='droits',
            name='readers',
            field=models.ManyToManyField(blank=True, to='fichiers_adherents.AccesFichier'),
        ),
    ]
