# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-08 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0008_auto_20170408_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrongnumber',
            name='adherent',
        ),
        migrations.RemoveField(
            model_name='wrongnumber',
            name='reported_by',
        ),
        migrations.DeleteModel(
            name='WrongNumber',
        ),
    ]
