# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0008_wrongnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherentdufichier',
            name='adherent',
        ),
        migrations.RemoveField(
            model_name='adherentdufichier',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='datedecotisation',
            name='adherents',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='importe_par_le_fichier',
        ),
        migrations.RemoveField(
            model_name='fichieradherents',
            name='nombre_nouveaux_adherents',
        ),
        migrations.RemoveField(
            model_name='fichieradherents',
            name='nombre_readhesions',
        ),
        migrations.AddField(
            model_name='adherent',
            name='fichier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fichiers_adherents.FichierAdherents'),
        ),
        migrations.AddField(
            model_name='adherent',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adherent',
            name='num_adherent',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='AdherentDuFichier',
        ),
        migrations.DeleteModel(
            name='DateDeCotisation',
        ),
    ]
