# Generated by Django 2.1.5 on 2019-02-07 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0009_auto_20170408_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichieradherents',
            name='importateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
