# Generated by Django 2.1.5 on 2019-02-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0010_auto_20190207_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adherent',
            options={'get_latest_by': 'fichier', 'ordering': ['nom'], 'permissions': (('lecture_fichier_national', 'peut lire le fichier national'),), 'verbose_name': 'adhérent', 'verbose_name_plural': 'adhérents'},
        ),
        migrations.AlterModelOptions(
            name='droits',
            options={'ordering': ['name'], 'verbose_name': "droit d'accès", 'verbose_name_plural': "droits d'accès"},
        ),
    ]
